<?php
  
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_ENTITY_TYPE_presave()
 */
function pezbase_data_node_presave(&$node) {
  if ($node->getType() == 'stem') {
    $tid = $node->get('field_patent_number')->target_id;
    $title_array[] = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($tid)->getName();

    $tid = $node->get('field_stem_color')->target_id;
    $title_array[] = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($tid)->getName();

    $title_array[] = $node->get('field_feet')->value;

    $id = $node->get('field_country_imc')->value;
    $allowed_values = $node->getFieldDefinition('field_country_imc')->getFieldStorageDefinition()->getSetting('allowed_values');
    $title_array[] = $allowed_values[$id];

    $ids = $node->get('field_stem_options');
    $allowed_values = $node->getFieldDefinition('field_stem_options')->getFieldStorageDefinition()->getSetting('allowed_values');
    foreach ($ids as $id) {
      $title_array[] = $allowed_values[$id->value];
    }

    $title_array[] = $node->get('field_printed_stem')->value;

    $title = implode(';', $title_array);
    // Todo: check that the title is unique.
    $node->title = $title;
  }
}
